### PR TITLE
Release qubes-i3status 1.6-2

### PR DESCRIPTION
**Pull request by anadahz**

### CODE REVIEW

**Comment by marmarek** [comment]
Use of `pactl` was intentional, `amixer` is hardware dependent, for example `Master` isn't always present. See https://github.com/QubesOS/qubes-issues/issues/5168#issuecomment-519511366
(github is misbehaving, so I can't add it as a review)

**Comment by anadahz** [comment]
@marmarek Thanks for the review.

I'm aware of https://github.com/QubesOS/qubes-issues/issues/5168#issuecomment-519511366 however in my setup and most probably in other i3 setups pactl keybindings are going to cause heavy sound distortion by over amplification. 

I discovered this issue by hearing too very bad sound distortion coming out of my speakers, it took me a while to find out that `pactl` doesn't stop at 100% when raising volume. See also: https://old.reddit.com/r/i3wm/comments/ahwb57/pulseaudio_exceeding_100_volume_with_keybindings/

**Comment by marmarek** [comment]
People are writing wrapping scripts for that...
But also it looks like some people _do_ want to set volume over 100%.

**Comment by anadahz** [comment]
Ok in 494cab1 I set `pactl` as the default volume control,  adding a optional config (as a comment) for users that prefer using `amixer`.

**Review by marmarek — APPROVED** [review]

**Pull request merged**
