### PR TITLE
Rework qubes-i3status in python and improve snd and net status

### LINKED ISSUE #9094: qubes-i3status - json invalid
### Qubes OS release
R4.2, testing repositories, latest update 

### Brief summary
after a dom0 update today, "qubes-i3status" started to generate invalid json causing issue with the i3 bar
The result of ``amixer sget Master`` in dom0 has changed.
The AWK command doesn't retrieve the correct thing now https://github.com/QubesOS/qubes-desktop-linux-i3-settings-qubes/blob/main/qubes-i3status#L138 (and it match multiple line, so it add control character in the json, making it invalid. 

Didn't had time to check what got modified

### PR DESCRIPTION
**Pull request by fepitre**
Closes QubesOS/qubes-issues#9094

### CODE REVIEW

**Comment by fepitre** [comment]
It needs testing and validation. I wrote it pretty straightforward without testing it on several machines.

**Comment by mpas97** [comment]
Thank you a lot for this rework. What I can observe (change in behaviour compared to current one):

- The qube count now shows one more. I get the same number including dom0.

- The whole status bar only refreshes around every 30s. Which is quite laggy, espacially for time showing the seconds. Before it was at least once per second, as time counts up as it should. (Running the new script in dom0 echoes every second though) I also observe this delay when restarting i3. The old version has direct output, the new only after some time

**Comment by fepitre** [comment]
> Thank you a lot for this rework. What I can observe (change in behaviour compared to current one):
> 
>     * The qube count now shows one more. I get the same number including dom0.

Yes, easy to fix.

>     * The whole status bar only refreshes around every 30s. Which is quite laggy, espacially for time showing the seconds. Before it was at least once per second, as time counts up as it should. (Running the new script in dom0 echoes every second though) I also observe this delay when restarting i3. The old version has direct output, the new only after some time

I need to investigate why it lags, it should not.

Thank you for your report.

**Comment by fepitre** [comment]
Ok, it should be fixed, I've also lower the refresh time to 2 seconds, notably for volume and load. I've also changed the display of running qubes. It handles none, only one and multiple.

**Comment by mpas97** [comment]
I really appreciate your work, looks all good or even better now.

**Comment by andrewdavidwong** [comment]
Suggestion: If you intend for this pull request to resolve the associated issue and would like for it to be [linked to the issue automatically](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), you can put `Closes QubesOS/qubes-issues#XXXX` in the PR and/or commit message (where `XXXX` is the issue number). `Closes` is one of several [special keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) that GitHub will recognize. If and when the PR is merged, GitHub will automatically close the associated issue.

**Comment by fepitre** [comment]
> Suggestion: If you intend for this pull request to resolve the associated issue and would like for it to be [linked to the issue automatically](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue), you can put `Closes QubesOS/qubes-issues#XXXX` in the PR and/or commit message (where `XXXX` is the issue number). `Closes` is one of several [special keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) that GitHub will recognize. If and when the PR is merged, GitHub will automatically close the associated issue.

Thank you, I'm aware of that. Indeed, it closes it.

**Comment by andrewdavidwong** [comment]
The reason I mentioned it is because your PR is not auto-linked to https://github.com/QubesOS/qubes-issues/issues/9094, so I guess it needs to be in the PR message instead of (or in addition to) the commit message.

**Comment by fepitre** [comment]
@marmarek friendly ping for merging this one please.

**Pull request merged**
